# Generated by Django 5.1.6 on 2025-03-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaryPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='submitted_at',
        ),
    ]
