# Generated by Django 5.1.6 on 2025-03-08 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaryPortfolio', '0002_remove_contactsubmission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
